name: Validate Gradle Wrapper
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  validation:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2
